# Generated by Django 3.1.14 on 2022-02-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.AddField(
            model_name='boutique',
            name='image',
            field=models.FileField(blank=True, upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='image',
            field=models.FileField(blank=True, upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.FileField(blank=True, upload_to='media/images'),
        ),
    ]
